version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm test
      - node_modeules/cdk/bin/cdk cdk synth > template.yml
artifacts:
  files:
    - 'functions/*.ts'
    - 'template.yml'