version: 0.2

phases:
  install:
    commands:
      - n 14.18.0
      - npm install -g aws-cdk 
  build:
    commands:
      - npm test
      - cdk synth > template.yml
artifacts:
  files:
    - 'functions/*.ts'
    - 'template.yml'