version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm install -g aws-cdk
  build:
    commands:
      - npm test
      - cdk synth > template.yml
artifacts:
  files:
    - 'functions/*.ts'
    - 'template.yml'
  name: 'cdk-build-artifact'   