version: 0.2

phases:
  install:
    commands:
      - npm install 
  build:
    commands:
      - npm test
      - node_modules/cdk/bin/cdk synth > template.yml
artifacts:
  files:
    - 'functions/*.ts'
    - 'template.yml'